# --- Input ---
rag_mode: false
retrieved_docs_dir: results/retrieved_docs_medqa_qwenagent/

# --- Model ---
model: "bartowski/google_gemma-3-27b-it-GGUF"
provider: "local"  # together | openai | local
local_base_url: "http://localhost:9500/v1"

# --- Output ---
output_file: "results/gemma3/results_gemma3_medqa_base.csv"
verbose: true
sufficient_only: false
