# --- Input ---
rag_mode: false
retrieved_docs_dir: results/retrieved_docs_medqa_qwen3/

# --- Model ---
model: "gpt-5-mini"
provider: "openai"  # together | openai | local
local_base_url: "http://localhost:8000/v1"

# --- Output ---
output_file: "results/gpt5mini/results_gpt5mini_medqa_base.csv"
verbose: true
